# Generated by Django 5.0.7 on 2026-01-04 14:55

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("admin", "Admin")],
                        default="user",
                        max_length=10,
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "email_notifications_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Master toggle for all email notifications",
                    ),
                ),
                (
                    "email_welcome",
                    models.BooleanField(default=True, help_text="Welcome emails"),
                ),
                (
                    "email_transactions",
                    models.BooleanField(
                        default=True, help_text="Transaction notifications"
                    ),
                ),
                (
                    "email_investments",
                    models.BooleanField(
                        default=True, help_text="Investment notifications"
                    ),
                ),
                (
                    "email_roi_payouts",
                    models.BooleanField(
                        default=True, help_text="ROI payout notifications"
                    ),
                ),
                (
                    "email_wallet_updates",
                    models.BooleanField(
                        default=True, help_text="Wallet credit/debit notifications"
                    ),
                ),
                (
                    "email_security_alerts",
                    models.BooleanField(default=True, help_text="Security alerts"),
                ),
                (
                    "email_marketing",
                    models.BooleanField(
                        default=False, help_text="Marketing and promotional emails"
                    ),
                ),
                (
                    "email_verified",
                    models.BooleanField(
                        default=False, help_text="Email address verified via code"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "users_profile",
            },
        ),
        migrations.CreateModel(
            name="UserWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "users_wallet",
            },
        ),
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "expires_at"],
                        name="users_email_user_id_86b0fe_idx",
                    ),
                    models.Index(fields=["token"], name="users_email_token_c80ef6_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="KycApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("personal_info", models.JSONField(blank=True, default=dict)),
                ("document_info", models.JSONField(blank=True, default=dict)),
                (
                    "personal_info_submitted_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("document_submitted_at", models.DateTimeField(blank=True, null=True)),
                ("last_submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewer_notes", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_kyc_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "users_kyc_application",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="users_kyc_a_status_cebdd4_idx"
                    ),
                    models.Index(
                        fields=["user", "status"], name="users_kyc_a_user_id_bee238_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("deposit_approved", "Deposit Approved"),
                            ("deposit_rejected", "Deposit Rejected"),
                            ("withdrawal_approved", "Withdrawal Approved"),
                            ("withdrawal_rejected", "Withdrawal Rejected"),
                            ("investment_approved", "Investment Approved"),
                            ("investment_rejected", "Investment Rejected"),
                            ("investment_completed", "Investment Completed"),
                            ("card_approved", "Virtual Card Approved"),
                            ("card_rejected", "Virtual Card Rejected"),
                            ("wallet_credited", "Wallet Credited"),
                            ("wallet_debited", "Wallet Debited"),
                            ("roi_payout", "ROI Payout"),
                            ("system_alert", "System Alert"),
                            ("welcome", "Welcome Message"),
                            ("kyc_submitted", "KYC Submitted"),
                            ("kyc_approved", "KYC Approved"),
                            ("kyc_rejected", "KYC Rejected"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "action_url",
                    models.CharField(
                        blank=True,
                        help_text="URL for user to take action",
                        max_length=255,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'transaction', 'investment'",
                        max_length=20,
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        blank=True,
                        help_text="UUID or ID of related entity",
                        max_length=100,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Auto-delete after this date", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Notification",
                "verbose_name_plural": "User Notifications",
                "db_table": "users_notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="users_notif_user_id_1be17e_idx",
                    ),
                    models.Index(
                        fields=["notification_type"],
                        name="users_notif_notific_af6ddd_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="users_notif_created_3ee999_idx"
                    ),
                    models.Index(
                        fields=["is_read"], name="users_notif_is_read_316047_idx"
                    ),
                    models.Index(
                        fields=["priority"], name="users_notif_priorit_29dabc_idx"
                    ),
                ],
            },
        ),
    ]
