# Generated by Django 5.0.7 on 2026-02-28 16:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KycDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('drivers_license', "Driver's License")], help_text='Type of government-issued ID', max_length=20)),
                ('document_file', models.FileField(help_text='Scanned copy of the document', upload_to='kyc_documents/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the document was submitted')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the document was reviewed', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if applicable')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kyc_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.kycapplication')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kyc_documents', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Document',
                'verbose_name_plural': 'KYC Documents',
                'db_table': 'users_kyc_document',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='users_kyc_d_user_id_05fa20_idx'), models.Index(fields=['document_type'], name='users_kyc_d_documen_0badb7_idx'), models.Index(fields=['status'], name='users_kyc_d_status_a9a2af_idx'), models.Index(fields=['created_at'], name='users_kyc_d_created_e671ef_idx')],
                'unique_together': {('user', 'document_type')},
            },
        ),
    ]
