# Generated by Django 5.0.7 on 2025-10-03 03:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('deposit_approved', 'Deposit Approved'), ('deposit_rejected', 'Deposit Rejected'), ('withdrawal_approved', 'Withdrawal Approved'), ('withdrawal_rejected', 'Withdrawal Rejected'), ('investment_approved', 'Investment Approved'), ('investment_rejected', 'Investment Rejected'), ('investment_completed', 'Investment Completed'), ('card_approved', 'Virtual Card Approved'), ('card_rejected', 'Virtual Card Rejected'), ('wallet_credited', 'Wallet Credited'), ('wallet_debited', 'Wallet Debited'), ('roi_payout', 'ROI Payout'), ('system_alert', 'System Alert'), ('welcome', 'Welcome Message')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, help_text='URL for user to take action', max_length=255)),
                ('entity_type', models.CharField(blank=True, help_text="e.g., 'transaction', 'investment'", max_length=20)),
                ('entity_id', models.CharField(blank=True, help_text='UUID or ID of related entity', max_length=100)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Auto-delete after this date', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Notification',
                'verbose_name_plural': 'User Notifications',
                'db_table': 'users_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='users_notif_user_id_1be17e_idx'), models.Index(fields=['notification_type'], name='users_notif_notific_af6ddd_idx'), models.Index(fields=['created_at'], name='users_notif_created_3ee999_idx'), models.Index(fields=['is_read'], name='users_notif_is_read_316047_idx'), models.Index(fields=['priority'], name='users_notif_priorit_29dabc_idx')],
            },
        ),
    ]
