# Generated by Django 5.0.7 on 2025-10-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_usernotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email_investments",
            field=models.BooleanField(default=True, help_text="Investment notifications"),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_marketing",
            field=models.BooleanField(default=False, help_text="Marketing and promotional emails"),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_notifications_enabled",
            field=models.BooleanField(
                default=True, help_text="Master toggle for all email notifications"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_roi_payouts",
            field=models.BooleanField(default=True, help_text="ROI payout notifications"),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_security_alerts",
            field=models.BooleanField(default=True, help_text="Security alerts"),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_transactions",
            field=models.BooleanField(default=True, help_text="Transaction notifications"),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_wallet_updates",
            field=models.BooleanField(default=True, help_text="Wallet credit/debit notifications"),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_welcome",
            field=models.BooleanField(default=True, help_text="Welcome emails"),
        ),
    ]
