# Generated by Django 5.2.1 on 2026-04-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('es', 'Spanish'), ('fr', 'French'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('no', 'Norwegian')], default='en', help_text="User's preferred language for the dashboard", max_length=10),
        ),
    ]
