# Generated by Django 5.0.7 on 2025-11-23 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_kycapplication_usernotification_notification_type"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="kycapplication",
            new_name="users_kyc_a_status_cebdd4_idx",
            old_name="users_kyc__status_3603a3_idx",
        ),
        migrations.RenameIndex(
            model_name="kycapplication",
            new_name="users_kyc_a_user_id_bee238_idx",
            old_name="users_kyc__user_id_e79dbf_idx",
        ),
    ]
