# Generated by Django 5.2.1 on 2026-04-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # This should match whatever was last in your 'users' migrations folder
        ('users', '0005_alter_userprofile_language_preference'), 
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language_preference',
            field=models.CharField(default='en', max_length=10, verbose_name='Language Preference'),
        ),
    ]

