# Generated by Django 5.2.1 on 2026-05-31 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userprofile_language_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdocument',
            name='document_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('national_id', 'National ID - Front'), ('national_id_back', 'National ID - Back'), ('drivers_license', "Driver's License"), ('proof_of_address', 'Proof of Address')], help_text='Type of government-issued ID', max_length=20),
        ),
    ]
