# Generated by Django 5.0.7 on 2025-12-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_profile_email_verified"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="emailverification",
            new_name="users_email_user_id_86b0fe_idx",
            old_name="email_verif_user_exp_idx",
        ),
        migrations.RenameIndex(
            model_name="emailverification",
            new_name="users_email_token_c80ef6_idx",
            old_name="email_verif_token_idx",
        ),
        migrations.AlterField(
            model_name="emailverification",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
