#!/bin/bash
# Quick Deployment Guide for WolvCapital

echo "🚀 WolvCapital Deployment Summary"
echo "=================================="
echo ""
echo "✅ Code Status: Pushed to GitHub"
echo "📦 Latest Commit: a8c137d"
echo "🌐 Repository: https://github.com/radical-workspace/solid-succotash"
echo ""
echo "🔑 Your Production SECRET_KEY:"
echo "ism+7l(h49h2v4(p9jg_9vlu)-m89nc_&pfztmavk_m4$6iwq*"
echo ""
echo "📋 Next Steps:"
echo "=============="
echo ""
echo "1. Go to Render.com Dashboard:"
echo "   👉 https://dashboard.render.com/"
echo ""
echo "2. Deploy using Blueprint (Easiest):"
echo "   - Click 'New +' → 'Blueprint'"
echo "   - Select: radical-workspace/solid-succotash"
echo "   - Set SECRET_KEY (shown above)"
echo "   - Click 'Apply'"
echo ""
echo "3. After deployment, run in Render Shell:"
echo "   python manage.py migrate"
echo "   python manage.py seed_plans"
echo "   python manage.py createsuperuser"
echo ""
echo "4. Visit your live site:"
echo "   https://your-app.onrender.com"
echo ""
echo "📖 Full checklist available in: DEPLOYMENT_CHECKLIST.md"
echo ""
