#!/bin/bash
# Quick start for WolvCapital checkout dev environment

echo "════════════════════════════════════════════════════════════════"
echo "   WolvCapital Checkout Feature - Dev Environment Setup"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "✅ Node.js is installed at: /tmp/node-v18.18.0-linux-x64"
echo "✅ Python venv exists at: /home/code/solid-succotash/.venv"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "   QUICK START (3 STEPS)"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "STEP 1: In Terminal 1 - Start Backend (Django API)"
echo "───────────────────────────────────────────────"
echo "  cd /home/code/solid-succotash"
echo "  export PATH=\"/tmp/node-v18.18.0-linux-x64/bin:\$PATH\""
echo "  bash run_backend.sh"
echo ""
echo "  Expected output:"
echo "    Starting development server at http://127.0.0.1:8000/"
echo ""
echo ""
echo "STEP 2: In Terminal 2 - Start Frontend (Next.js)"
echo "────────────────────────────────────────────────"
echo "  cd /home/code/solid-succotash"
echo "  export PATH=\"/tmp/node-v18.18.0-linux-x64/bin:\$PATH\""
echo "  bash run_frontend.sh"
echo ""
echo "  Expected output:"
echo "    ▲ Next.js 14.0.0"
echo "    - Local: http://localhost:3000"
echo ""
echo ""
echo "STEP 3: Test the Checkout Flow"
echo "──────────────────────────────"
echo "  1. Open browser: http://localhost:3000/checkout"
echo "  2. Enter customer name (e.g., \"John Doe\")"
echo "  3. Enter customer email (e.g., \"test@example.com\")"
echo "  4. Click \"Add to checkout\" on an item"
echo "  5. Click \"Complete checkout\""
echo "  6. Should redirect to /checkout/success"
echo "  7. Email should be sent to API with Trustpilot BCC"
echo "  8. Trustpilot invite widget appears"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "   WHAT WAS BUILT"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "✅ Frontend Checkout Pages:"
echo "   - /checkout - Customer form + item selection"
echo "   - /checkout/success - Completion page + Trustpilot widget"
echo ""
echo "✅ Backend API Endpoint:"
echo "   - POST /api/checkout/completion/"
echo "   - Sends email with Trustpilot BCC invite"
echo ""
echo "✅ Email Integration:"
echo "   - Sends checkout completion email with Trustpilot BCC"
echo "   - Auto-triggers on success page load"
echo "   - Trustpilot invitation email sent to customer"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "   TROUBLESHOOTING"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "If backend fails with \"No module named django\":"
echo "  • The venv might need dependencies installed"
echo "  • Try: cd /home/code/solid-succotash && .venv/bin/python manage.py migrate"
echo ""
echo "If frontend fails with npm errors:"
echo "  • Delete node_modules: rm -rf /home/code/solid-succotash/frontend/node_modules"
echo "  • Reinstall: cd /home/code/solid-succotash/frontend && npm install --legacy-peer-deps"
echo ""
echo "If port 8000 or 3000 is in use:"
echo "  • Find: lsof -i :8000 (or :3000)"
echo "  • Kill: kill -9 <PID>"
echo ""
echo "════════════════════════════════════════════════════════════════"
