#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
WolvCapital Render.com Deployment Configuration Script

This script generates the required environment variables for Render.com deployment.
Run this locally, then copy the output to your Render dashboard Environment section.
"""

import secrets
import sys


def generate_secret_key():
    """Generate a secure Django SECRET_KEY"""
    return secrets.token_urlsafe(50)


def print_env_vars():
    """Print all required environment variables for Render deployment"""
    
    secret_key = generate_secret_key()
    
    print("=" * 80)
    print("WOLVCAPITAL - RENDER.COM ENVIRONMENT VARIABLES")
    print("=" * 80)
    print("\nCopy these to your Render Dashboard → Environment:\n")
    print("-" * 80)
    
    # Essential Django Settings
    print("\n# Django Core Settings")
    print(f"SECRET_KEY={secret_key}")
    print("DEBUG=0")
    print("")
    
    # Email Configuration
    print("# Email Configuration (REQUIRED - Update with your SMTP details)")
    print("EMAIL_HOST=smtp.gmail.com")
    print("EMAIL_PORT=587")
    print("EMAIL_USE_TLS=True")
    print("EMAIL_HOST_USER=noreply@wolvcapital.com  # ← UPDATE THIS")
    print("EMAIL_HOST_PASSWORD=your-gmail-app-password-here  # ← UPDATE THIS")
    print("DEFAULT_FROM_EMAIL=WolvCapital <noreply@wolvcapital.com>")
    print("")
    
    # Admin Email Recipients
    print("# Admin Email Recipients (Contact Form notifications)")
    print("ADMIN_EMAIL_RECIPIENTS=admin@wolvcapital.com,support@wolvcapital.com,finance@wolvcapital.com,compliance@wolvcapital.com,operations@wolvcapital.com  # ← UPDATE WITH YOUR EMAILS")
    print("")
    
    # CORS Settings
    print("# CORS Settings (for Next.js frontend)")
    print("CORS_ALLOWED_ORIGINS=https://wolvcapital.com,https://www.wolvcapital.com,https://wolvcapital.vercel.app  # ← UPDATE WITH YOUR FRONTEND URLS")
    print("CSRF_TRUSTED_ORIGINS=https://wolvcapital.com,https://www.wolvcapital.com")
    print("")
    
    # Optional Settings
    print("# Optional Settings")
    print("CUSTOM_DOMAIN=wolvcapital.com  # ← UPDATE IF USING CUSTOM DOMAIN")
    print("SITE_URL=https://api.wolvcapital.com  # ← Will be set by RENDER_EXTERNAL_URL")
    print("PUBLIC_SITE_URL=https://wolvcapital.com")
    print("")
    
    print("-" * 80)
    print("\n✓ SECRET_KEY has been generated")
    print("✓ Copy all variables above to Render Dashboard")
    print("✓ Update EMAIL_* values with your SMTP credentials")
    print("✓ Update ADMIN_EMAIL_RECIPIENTS with your admin emails")
    print("✓ Update CORS_ALLOWED_ORIGINS with your frontend URLs")
    print("\n" + "=" * 80)
    print("\nIMPORTANT EMAIL SETUP NOTES:")
    print("-" * 80)
    print("""
For Gmail SMTP:
1. Enable 2-Factor Authentication on your Google Account
2. Generate an App Password:
   - Go to: https://myaccount.google.com/apppasswords
   - Select 'Mail' and your device
   - Copy the 16-character password (remove spaces)
   - Use this as EMAIL_HOST_PASSWORD

For Other Email Providers:
- SendGrid: Use SMTP relay with API key
- Mailgun: smtp.mailgun.org, port 587
- Amazon SES: Configure SMTP credentials in AWS console
- Office 365: smtp.office365.com, port 587

Test Email After Deployment:
1. SSH into Render shell or use Django admin
2. Send a test email from /contact/ form
3. Check spam folder if emails don't arrive
    """)
    print("=" * 80)


def generate_local_env():
    """Generate .env file for local development"""
    
    secret_key = generate_secret_key()
    
    env_content = f"""# WolvCapital Local Development Environment
# Generated by render_config.py

# Django Settings
DEBUG=1
SECRET_KEY={secret_key}

# Database (SQLite for local, Render provides DATABASE_URL in production)
# DATABASE_URL=sqlite:///db.sqlite3

# Email Configuration (Console backend for local development)
EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
EMAIL_HOST=smtp.gmail.com
EMAIL_PORT=587
EMAIL_USE_TLS=True
EMAIL_HOST_USER=your-email@gmail.com
EMAIL_HOST_PASSWORD=your-app-password
DEFAULT_FROM_EMAIL=WolvCapital <noreply@wolvcapital.com>

# Admin Email Recipients
ADMIN_EMAIL_RECIPIENTS=admin@localhost,support@localhost

# Local URLs
SITE_URL=http://localhost:8000
PUBLIC_SITE_URL=http://localhost:3000

# CORS (for Next.js frontend)
CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
"""
    
    with open('.env', 'w') as f:
        f.write(env_content)
    
    print("\n✓ .env file created for local development")
    print("  - DEBUG=1 (development mode)")
    print("  - EMAIL_BACKEND=console (emails print to terminal)")
    print("  - SQLite database")
    print("\nTo use: Just run 'python manage.py runserver'")


if __name__ == "__main__":
    print_env_vars()
    
    # Ask if user wants to generate local .env
    print("\n" + "=" * 80)
    response = input("Generate .env file for local development? (y/n): ").strip().lower()
    if response == 'y':
        generate_local_env()
    
    print("\n✓ Configuration complete!")
