# Generated by Django 5.0.7 on 2025-10-10 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Stable identifier used in links and lookups.')),
                ('version', models.CharField(help_text='Semantic version label, e.g., 1.0.0', max_length=20)),
                ('body', models.TextField(help_text='Markdown/plain-text body rendered for the user.')),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-effective_date', '-created_at'],
                'unique_together': {('slug', 'version')},
            },
        ),
        migrations.CreateModel(
            name='UserAgreementAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('agreement_hash', models.CharField(blank=True, help_text='SHA256 hash of agreement body at acceptance time', max_length=64)),
                ('agreement_version', models.CharField(blank=True, help_text='Version string captured at acceptance time', max_length=20)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.agreement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accepted_at'],
                'unique_together': {('user', 'agreement')},
            },
        ),
    ]
