# Generated by Django 5.0.7 on 2026-01-05 11:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IncomingEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=512)),
                ("sender", models.CharField(blank=True, max_length=512)),
                ("recipients", models.CharField(blank=True, max_length=1024)),
                ("body", models.TextField(blank=True)),
                ("raw_date", models.CharField(blank=True, max_length=128)),
                ("received_by", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlatformCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Certificate of Operation", max_length=255
                    ),
                ),
                ("certificate_id", models.CharField(max_length=64, unique=True)),
                ("issue_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "jurisdiction",
                    models.CharField(default="United States", max_length=255),
                ),
                (
                    "issuing_authority",
                    models.CharField(
                        help_text="Name of the issuing authority", max_length=255
                    ),
                ),
                ("verification_url", models.URLField(blank=True, max_length=500)),
                ("authority_seal_url", models.URLField(blank=True, max_length=500)),
                ("signature_1_url", models.URLField(blank=True, max_length=500)),
                ("signature_2_url", models.URLField(blank=True, max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Agreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Stable identifier used in links and lookups."
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Semantic version label, e.g., 1.0.0", max_length=20
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Markdown/plain-text body rendered for the user."
                    ),
                ),
                ("effective_date", models.DateField(default=django.utils.timezone.now)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-effective_date", "-created_at"],
                "unique_together": {("slug", "version")},
            },
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("subject", models.CharField(max_length=500)),
                (
                    "body",
                    models.TextField(help_text="Use {{variable}} for placeholders"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Support, Sales, Billing",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="EmailAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="email_attachments/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="core.incomingemail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupportRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("topic", models.CharField(blank=True, max_length=120)),
                ("source_url", models.CharField(blank=True, max_length=255)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_support_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailInbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        help_text="Unique email message ID", max_length=255, unique=True
                    ),
                ),
                ("subject", models.CharField(max_length=500)),
                ("from_email", models.EmailField(max_length=254)),
                ("from_name", models.CharField(blank=True, max_length=255)),
                ("to_email", models.EmailField(max_length=254)),
                (
                    "cc",
                    models.TextField(
                        blank=True, help_text="Comma-separated CC recipients"
                    ),
                ),
                (
                    "bcc",
                    models.TextField(
                        blank=True, help_text="Comma-separated BCC recipients"
                    ),
                ),
                ("reply_to", models.EmailField(blank=True, max_length=254)),
                ("body_text", models.TextField(help_text="Plain text version")),
                ("body_html", models.TextField(blank=True, help_text="HTML version")),
                ("has_attachments", models.BooleanField(default=False)),
                (
                    "attachment_info",
                    models.JSONField(
                        blank=True, default=dict, help_text="Attachment metadata"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unread", "Unread"),
                            ("read", "Read"),
                            ("replied", "Replied"),
                            ("archived", "Archived"),
                            ("spam", "Spam"),
                        ],
                        default="unread",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("is_starred", models.BooleanField(default=False)),
                (
                    "labels",
                    models.CharField(
                        blank=True, help_text="Comma-separated labels", max_length=255
                    ),
                ),
                ("folder", models.CharField(default="inbox", max_length=50)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("replied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "received_at",
                    models.DateTimeField(
                        help_text="When email was received by mail server"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When fetched into system"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("raw_headers", models.JSONField(blank=True, default=dict)),
                (
                    "raw_email",
                    models.TextField(
                        blank=True, help_text="Complete raw email for forensics"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin user handling this email",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email",
                "verbose_name_plural": "Inbox",
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["-received_at"], name="core_emaili_receive_556cd4_idx"
                    ),
                    models.Index(
                        fields=["status"], name="core_emaili_status_5ca237_idx"
                    ),
                    models.Index(
                        fields=["from_email"], name="core_emaili_from_em_cf16f7_idx"
                    ),
                    models.Index(
                        fields=["assigned_to"], name="core_emaili_assigne_f209f6_idx"
                    ),
                    models.Index(
                        fields=["is_starred"], name="core_emaili_is_star_aea0b3_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserAgreementAcceptance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accepted_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "agreement_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA256 hash of agreement body at acceptance time",
                        max_length=64,
                    ),
                ),
                (
                    "agreement_version",
                    models.CharField(
                        blank=True,
                        help_text="Version string captured at acceptance time",
                        max_length=20,
                    ),
                ),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.agreement"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-accepted_at"],
                "unique_together": {("user", "agreement")},
            },
        ),
    ]
