# Generated by Django 5.0.7 on 2025-10-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useragreementacceptance',
            name='agreement_hash',
            field=models.CharField(blank=True, help_text='SHA256 hash of agreement body at acceptance time', max_length=64),
        ),
        migrations.AddField(
            model_name='useragreementacceptance',
            name='agreement_version',
            field=models.CharField(blank=True, help_text='Version string captured at acceptance time', max_length=20),
        ),
    ]
