# Generated by Django 5.2.1 on 2026-05-07 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platformcertificate',
            options={},
        ),
        migrations.CreateModel(
            name='DripCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_day', models.IntegerField(default=1, help_text='Current day of campaign (1-10)')),
                ('last_sent', models.DateTimeField(blank=True, help_text='Timestamp of last email sent', null=True)),
                ('active', models.BooleanField(default=True, help_text='Whether the campaign is actively sending emails')),
                ('completed', models.BooleanField(default=False, help_text='Whether user finished all 10 emails')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, help_text='When user was enrolled in campaign')),
                ('user', models.OneToOneField(help_text='User enrolled in the campaign', on_delete=django.db.models.deletion.CASCADE, related_name='drip_campaign', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Drip Campaign',
                'verbose_name_plural': 'Drip Campaigns',
                'ordering': ['-enrolled_at'],
            },
        ),
    ]
