# Generated by Copilot for campaign announcements

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_platformcertificate_options_dripcampaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.CharField(blank=True, max_length=320)),
                ('body', models.TextField(blank=True)),
                ('cta_label', models.CharField(blank=True, max_length=80)),
                ('cta_url', models.URLField(blank=True, max_length=200)),
                ('publish_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campaign Announcement',
                'verbose_name_plural': 'Campaign Announcements',
                'ordering': ['-publish_at', '-created_at'],
            },
        ),
    ]