# Generated by Django 5.0.7 on 2025-11-26 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_emailtemplate_emailinbox"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncomingEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=512)),
                ("sender", models.CharField(blank=True, max_length=512)),
                ("recipients", models.CharField(blank=True, max_length=1024)),
                ("body", models.TextField(blank=True)),
                ("raw_date", models.CharField(blank=True, max_length=128)),
                ("received_by", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmailAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="email_attachments/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="core.incomingemail",
                    ),
                ),
            ],
        ),
    ]
