# Generated by Django 5.0.7 on 2025-12-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_enable_rls_user_scoping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformcertificate",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
