# Generated by Django 5.0.7 on 2026-01-04 14:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyRoiPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payout_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-payout_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserInvestment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "investments_user_investment",
            },
        ),
        migrations.CreateModel(
            name="InvestmentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "daily_roi",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Daily ROI percentage (0.00-2.00)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("2.00")),
                        ],
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("min_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("max_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "investments_plan",
                "indexes": [
                    models.Index(fields=["name"], name="investments_name_2248e3_idx"),
                    models.Index(
                        fields=["created_at"], name="investments_created_1f6b3e_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="investmentplan",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("daily_roi__gte", Decimal("0.00")),
                    ("daily_roi__lte", Decimal("2.00")),
                ),
                name="valid_daily_roi",
            ),
        ),
        migrations.AddConstraint(
            model_name="investmentplan",
            constraint=models.CheckConstraint(
                check=models.Q(("duration_days__gt", 0)), name="positive_duration"
            ),
        ),
        migrations.AddConstraint(
            model_name="investmentplan",
            constraint=models.CheckConstraint(
                check=models.Q(("min_amount__lte", models.F("max_amount"))),
                name="min_amount_lte_max_amount",
            ),
        ),
        migrations.AddField(
            model_name="userinvestment",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_investments",
                to="investments.investmentplan",
            ),
        ),
    ]
