# Generated by Django 5.0.7 on 2026-01-04 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("investments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userinvestment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="investments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dailyroipayout",
            name="investment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_payouts",
                to="investments.userinvestment",
            ),
        ),
        migrations.AddIndex(
            model_name="userinvestment",
            index=models.Index(
                fields=["user", "status"], name="investments_user_id_66c729_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userinvestment",
            index=models.Index(fields=["status"], name="investments_status_4e7b70_idx"),
        ),
        migrations.AddIndex(
            model_name="userinvestment",
            index=models.Index(
                fields=["created_at"], name="investments_created_72262d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="userinvestment",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gt", 0)), name="positive_investment_amount"
            ),
        ),
        migrations.AddIndex(
            model_name="dailyroipayout",
            index=models.Index(
                fields=["payout_date"], name="investments_payout__eff298_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailyroipayout",
            unique_together={("investment", "payout_date")},
        ),
    ]
