# Generated by GitHub Copilot

from __future__ import annotations

from decimal import Decimal

from django.db import migrations


def sync_canonical_plans(apps, schema_editor):
    InvestmentPlan = apps.get_model("investments", "InvestmentPlan")

    plans = [
        {
            "name": "Pioneer",
            "description": "Entry-level plan for new investors (90-day term).",
            "daily_roi": Decimal("1.00"),
            "duration_days": 90,
            "min_amount": Decimal("100"),
            "max_amount": Decimal("999"),
        },
        {
            "name": "Vanguard",
            "description": "Balanced growth plan (150-day term).",
            "daily_roi": Decimal("1.25"),
            "duration_days": 150,
            "min_amount": Decimal("1000"),
            "max_amount": Decimal("4999"),
        },
        {
            "name": "Horizon",
            "description": "Advanced plan for experienced investors (180-day term).",
            "daily_roi": Decimal("1.50"),
            "duration_days": 180,
            "min_amount": Decimal("5000"),
            "max_amount": Decimal("14999"),
        },
        {
            "name": "Summit",
            "description": "Premium annual plan for high allocations (365-day term).",
            "daily_roi": Decimal("2.00"),
            "duration_days": 365,
            "min_amount": Decimal("15000"),
            "max_amount": Decimal("100000"),
        },
    ]

    for plan in plans:
        name = plan["name"]
        defaults = {k: v for k, v in plan.items() if k != "name"}
        InvestmentPlan.objects.update_or_create(name=name, defaults=defaults)


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0002_initial"),
    ]

    operations = [
        migrations.RunPython(sync_canonical_plans, reverse_code=migrations.RunPython.noop),
    ]
