# Generated by Django 5.0.7 on 2026-01-08 22:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0003_sync_canonical_plans"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="dailyroipayout",
            name="investments_payout__eff298_idx",
        ),
        migrations.RemoveIndex(
            model_name="investmentplan",
            name="investments_name_2248e3_idx",
        ),
        migrations.RemoveIndex(
            model_name="investmentplan",
            name="investments_created_1f6b3e_idx",
        ),
        migrations.RemoveIndex(
            model_name="userinvestment",
            name="investments_user_id_66c729_idx",
        ),
        migrations.RemoveIndex(
            model_name="userinvestment",
            name="investments_status_4e7b70_idx",
        ),
        migrations.RemoveIndex(
            model_name="userinvestment",
            name="investments_created_72262d_idx",
        ),
        migrations.AlterField(
            model_name="investmentplan",
            name="daily_roi",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Daily ROI percentage (0.00–2.00)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("2.00")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userinvestment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="userinvestment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
