# Generated by Django 5.0.7 on 2026-01-11 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "investments",
            "0004_remove_dailyroipayout_investments_payout__eff298_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyroipayout",
            name="processed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this payout was credited to wallet (idempotency)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dailyroipayout",
            name="transaction_id",
            field=models.UUIDField(
                blank=True, help_text="Related completed Transaction record", null=True
            ),
        ),
    ]
