# Generated by Django 5.0.7 on 2026-01-15 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0005_add_roi_payout_auto_credit_fields"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dailyroipayout",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="dailyroipayout",
            name="credited_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this payout was credited to wallet",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dailyroipayout",
            name="credited_tx",
            field=models.UUIDField(
                blank=True, help_text="Related Transaction record", null=True
            ),
        ),
        migrations.AlterField(
            model_name="dailyroipayout",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name="dailyroipayout",
            name="investment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="investments.userinvestment",
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyroipayout",
            constraint=models.UniqueConstraint(
                fields=("investment", "payout_date"),
                name="uniq_roi_payout_per_investment_per_day",
            ),
        ),
        migrations.RemoveField(
            model_name="dailyroipayout",
            name="processed_at",
        ),
        migrations.RemoveField(
            model_name="dailyroipayout",
            name="transaction_id",
        ),
    ]
