# Generated by Django 5.0.7 on 2026-01-04 14:55

import django.core.validators
import referrals.models
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reward_processed", models.BooleanField(default=False)),
                ("reward_processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("credited", "Credited"),
                            ("rejected", "Rejected"),
                            ("flagged", "Flagged"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("meta", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Referral",
                "verbose_name_plural": "Referrals",
                "db_table": "referrals",
            },
        ),
        migrations.CreateModel(
            name="ReferralCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=referrals.models.gen_code, max_length=32, unique=True
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Referral Code",
                "verbose_name_plural": "Referral Codes",
                "db_table": "referral_codes",
            },
        ),
        migrations.CreateModel(
            name="ReferralReward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("signup_bonus", "Signup Bonus"),
                            ("deposit_pct", "Deposit Percentage"),
                            ("manual", "Manual Grant"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Referral Reward",
                "verbose_name_plural": "Referral Rewards",
                "db_table": "referral_rewards",
            },
        ),
        migrations.CreateModel(
            name="ReferralSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("value", models.JSONField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Referral Setting",
                "verbose_name_plural": "Referral Settings",
                "db_table": "referral_settings",
            },
        ),
    ]
