# Generated by Django 5.0.7 on 2025-11-30 05:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="referral",
            options={"verbose_name": "Referral", "verbose_name_plural": "Referrals"},
        ),
        migrations.AlterModelOptions(
            name="referralcode",
            options={
                "verbose_name": "Referral Code",
                "verbose_name_plural": "Referral Codes",
            },
        ),
        migrations.AlterModelOptions(
            name="referralreward",
            options={
                "verbose_name": "Referral Reward",
                "verbose_name_plural": "Referral Rewards",
            },
        ),
        migrations.AlterModelOptions(
            name="referralsetting",
            options={
                "verbose_name": "Referral Setting",
                "verbose_name_plural": "Referral Settings",
            },
        ),
        migrations.RenameIndex(
            model_name="referral",
            new_name="referrals_referre_ebd676_idx",
            old_name="referrals_r_referre_05eb1c_idx",
        ),
        migrations.RenameIndex(
            model_name="referral",
            new_name="referrals_referre_f47e8e_idx",
            old_name="referrals_r_referre_18a7a2_idx",
        ),
        migrations.RenameIndex(
            model_name="referral",
            new_name="referrals_code_2ba851_idx",
            old_name="referrals_r_code_559b5e_idx",
        ),
        migrations.AddIndex(
            model_name="referral",
            index=models.Index(fields=["status"], name="referrals_status_135a0e_idx"),
        ),
        migrations.AlterModelTable(
            name="referral",
            table="referrals",
        ),
        migrations.AlterModelTable(
            name="referralcode",
            table="referral_codes",
        ),
        migrations.AlterModelTable(
            name="referralreward",
            table="referral_rewards",
        ),
        migrations.AlterModelTable(
            name="referralsetting",
            table="referral_settings",
        ),
    ]
