# Generated by Django 5.0.7 on 2026-01-04 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("referrals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="referred_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referred_referrals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="referrer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrals_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="referralcode",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referral_code",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="referralreward",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="referralreward",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="referralreward",
            name="referral",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rewards",
                to="referrals.referral",
            ),
        ),
        migrations.AddIndex(
            model_name="referral",
            index=models.Index(
                fields=["referred_user"], name="referrals_referre_ebd676_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referral",
            index=models.Index(
                fields=["referrer"], name="referrals_referre_f47e8e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referral",
            index=models.Index(fields=["code"], name="referrals_code_2ba851_idx"),
        ),
        migrations.AddIndex(
            model_name="referral",
            index=models.Index(fields=["status"], name="referrals_status_135a0e_idx"),
        ),
    ]
