# Generated by Django 5.0.7 on 2025-09-18 23:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity', models.CharField(choices=[('transaction', 'Transaction'), ('investment', 'Investment'), ('plan', 'Plan'), ('user', 'User')], max_length=20)),
                ('entity_id', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('update', 'Update'), ('create', 'Create')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin'], name='transaction_admin_i_f1f71c_idx'), models.Index(fields=['entity', 'entity_id'], name='transaction_entity_fa1d1b_idx'), models.Index(fields=['created_at'], name='transaction_created_fbf51f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tx_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('reference', models.TextField(help_text='Reference number, notes, or proof of payment')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Admin notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transactions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions_transaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='transaction_user_id_9cef77_idx'), models.Index(fields=['tx_type', 'status'], name='transaction_tx_type_f78b2a_idx'), models.Index(fields=['created_at'], name='transaction_created_67ce7b_idx'), models.Index(fields=['status'], name='transaction_status_71abbb_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='positive_transaction_amount'),
        ),
    ]
