# Generated by Django 5.0.7 on 2026-01-04 14:55

import django.core.validators
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity",
                    models.CharField(
                        choices=[
                            ("transaction", "Transaction"),
                            ("investment", "Investment"),
                            ("plan", "Plan"),
                            ("user", "User"),
                            ("kyc", "KYC Application"),
                        ],
                        max_length=20,
                    ),
                ),
                ("entity_id", models.CharField(max_length=100)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("update", "Update"),
                            ("create", "Create"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "transactions_audit_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdminNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("new_deposit", "New Deposit Request"),
                            ("new_withdrawal", "New Withdrawal Request"),
                            ("new_investment", "New Investment Request"),
                            ("new_card_request", "New Virtual Card Request"),
                            ("user_registration", "New User Registration"),
                            ("new_kyc", "New KYC Submission"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("entity_type", models.CharField(blank=True, max_length=20, null=True)),
                ("entity_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Admin Notification",
                "verbose_name_plural": "Admin Notifications",
                "db_table": "transactions_admin_notification",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CryptocurrencyWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("BTC", "Bitcoin"),
                            ("USDT", "Tether USD"),
                            ("USDC", "USD Coin"),
                            ("ETH", "Ethereum"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "wallet_address",
                    models.CharField(
                        help_text="Wallet address for receiving deposits",
                        max_length=255,
                    ),
                ),
                (
                    "network",
                    models.CharField(
                        blank=True,
                        help_text="Network (e.g., ERC-20, TRC-20, BEP-20)",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this wallet is accepting deposits",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cryptocurrency Wallet",
                "verbose_name_plural": "Cryptocurrency Wallets",
                "db_table": "transactions_crypto_wallet",
                "ordering": ["currency"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tx_type",
                    models.CharField(
                        choices=[("deposit", "Deposit"), ("withdrawal", "Withdrawal")],
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("bank_transfer", "Bank Transfer"),
                            ("BTC", "Bitcoin"),
                            ("USDT", "Tether USD"),
                            ("USDC", "USD Coin"),
                            ("ETH", "Ethereum"),
                        ],
                        default="bank_transfer",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "reference",
                    models.TextField(
                        help_text="Reference number, notes, or proof of payment"
                    ),
                ),
                (
                    "tx_hash",
                    models.CharField(
                        blank=True,
                        help_text="Cryptocurrency transaction hash",
                        max_length=255,
                    ),
                ),
                (
                    "wallet_address_used",
                    models.CharField(
                        blank=True,
                        help_text="Wallet address used for crypto deposit",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Admin notes")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "transactions_transaction",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VirtualCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "card_type",
                    models.CharField(
                        choices=[("visa", "Visa Virtual Card")],
                        default="visa",
                        max_length=20,
                    ),
                ),
                (
                    "card_number",
                    models.CharField(
                        blank=True, help_text="Generated card number", max_length=16
                    ),
                ),
                ("cardholder_name", models.CharField(blank=True, max_length=100)),
                ("expiry_month", models.CharField(blank=True, max_length=2)),
                ("expiry_year", models.CharField(blank=True, max_length=2)),
                ("cvv", models.CharField(blank=True, max_length=3)),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "purchase_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1000.00"), max_digits=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, help_text="Admin notes")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Virtual Card",
                "verbose_name_plural": "Virtual Cards",
                "db_table": "transactions_virtual_card",
                "ordering": ["-created_at"],
            },
        ),
    ]
