# Generated by Django 5.0.7 on 2026-01-04 14:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transactions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="adminauditlog",
            name="admin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="adminnotification",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="adminnotification",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="virtualcard",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_cards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="virtualcard",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="virtual_cards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="adminauditlog",
            index=models.Index(fields=["admin"], name="transaction_admin_i_f1f71c_idx"),
        ),
        migrations.AddIndex(
            model_name="adminauditlog",
            index=models.Index(
                fields=["entity", "entity_id"], name="transaction_entity_fa1d1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminauditlog",
            index=models.Index(
                fields=["created_at"], name="transaction_created_fbf51f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminnotification",
            index=models.Index(
                fields=["notification_type"], name="transaction_notific_ccddb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminnotification",
            index=models.Index(
                fields=["is_read"], name="transaction_is_read_063eee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminnotification",
            index=models.Index(
                fields=["is_resolved"], name="transaction_is_reso_dc4d2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminnotification",
            index=models.Index(
                fields=["priority"], name="transaction_priorit_4fc7fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminnotification",
            index=models.Index(
                fields=["created_at"], name="transaction_created_8ae28f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminnotification",
            index=models.Index(fields=["user"], name="transaction_user_id_0a7338_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "status"], name="transaction_user_id_9cef77_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["tx_type", "status"], name="transaction_tx_type_f78b2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["payment_method"], name="transaction_payment_77b5ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["created_at"], name="transaction_created_67ce7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["status"], name="transaction_status_71abbb_idx"),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gt", Decimal("0.00"))),
                name="positive_transaction_amount",
            ),
        ),
        migrations.AddConstraint(
            model_name="virtualcard",
            constraint=models.CheckConstraint(
                check=models.Q(("balance__gte", Decimal("0.00"))),
                name="positive_card_balance",
            ),
        ),
        migrations.AddConstraint(
            model_name="virtualcard",
            constraint=models.CheckConstraint(
                check=models.Q(("purchase_amount__gt", Decimal("0.00"))),
                name="positive_purchase_amount",
            ),
        ),
    ]
