# Generated by Django 5.0.7 on 2025-09-19 02:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transactions",
            "0002_cryptocurrencywallet_transaction_payment_method_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VirtualCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "card_type",
                    models.CharField(
                        choices=[("visa", "Visa Virtual Card")],
                        default="visa",
                        max_length=20,
                    ),
                ),
                (
                    "card_number",
                    models.CharField(blank=True, help_text="Generated card number", max_length=16),
                ),
                ("cardholder_name", models.CharField(blank=True, max_length=100)),
                ("expiry_month", models.CharField(blank=True, max_length=2)),
                ("expiry_year", models.CharField(blank=True, max_length=2)),
                ("cvv", models.CharField(blank=True, max_length=3)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "purchase_amount",
                    models.DecimalField(decimal_places=2, default=1000, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, help_text="Admin notes")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="virtual_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Virtual Card",
                "verbose_name_plural": "Virtual Cards",
                "db_table": "transactions_virtual_card",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdminNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("new_deposit", "New Deposit Request"),
                            ("new_withdrawal", "New Withdrawal Request"),
                            ("new_investment", "New Investment Request"),
                            ("new_card_request", "New Virtual Card Request"),
                            ("user_registration", "New User Registration"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("entity_type", models.CharField(blank=True, max_length=20, null=True)),
                ("entity_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Notification",
                "verbose_name_plural": "Admin Notifications",
                "db_table": "transactions_admin_notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["notification_type"],
                        name="transaction_notific_ccddb2_idx",
                    ),
                    models.Index(fields=["is_read"], name="transaction_is_read_063eee_idx"),
                    models.Index(fields=["is_resolved"], name="transaction_is_reso_dc4d2a_idx"),
                    models.Index(fields=["priority"], name="transaction_priorit_4fc7fa_idx"),
                    models.Index(fields=["created_at"], name="transaction_created_8ae28f_idx"),
                    models.Index(fields=["user"], name="transaction_user_id_0a7338_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="virtualcard",
            constraint=models.CheckConstraint(
                check=models.Q(("balance__gte", 0)), name="positive_card_balance"
            ),
        ),
        migrations.AddConstraint(
            model_name="virtualcard",
            constraint=models.CheckConstraint(
                check=models.Q(("purchase_amount__gt", 0)),
                name="positive_purchase_amount",
            ),
        ),
    ]
