# Generated by Django 5.0.7 on 2026-01-11 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0005_add_roi_payout_auto_credit_fields"),
        ("transactions", "0003_add_completed_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="investment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="investments.userinvestment",
            ),
        ),
        migrations.AlterField(
            model_name="adminauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("approve", "Approve"),
                    ("reject", "Reject"),
                    ("update", "Update"),
                    ("create", "Create"),
                    ("auto_credit", "Auto Credit"),
                    ("recalculate_end_date", "Recalculate End Date"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="adminauditlog",
            name="entity",
            field=models.CharField(
                choices=[
                    ("transaction", "Transaction"),
                    ("investment", "Investment"),
                    ("plan", "Plan"),
                    ("user", "User"),
                    ("kyc", "KYC Application"),
                    ("roi_payout", "ROI Payout"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="tx_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("withdrawal", "Withdrawal"),
                    ("profit", "Profit"),
                ],
                max_length=20,
            ),
        ),
    ]
