# Generated by Django 5.0.7 on 2026-01-15 04:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0006_alter_dailyroipayout_unique_together_and_more"),
        ("transactions", "0004_add_profit_transaction_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                fields=("reference",), name="uniq_transaction_reference"
            ),
        ),
    ]
