# Generated by Django 5.0.7 on 2026-04-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_adminauditlog_card_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminauditlog',
            name='card_pin',
        ),
        migrations.AddField(
            model_name='virtualcard',
            name='card_pin',
            field=models.CharField(blank=True, help_text='Hashed card security PIN — set by admin on approval, NOT the account password', max_length=255, null=True),
        ),
    ]
