# Generated by Django 5.2.1 on 2026-05-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_remove_adminauditlog_card_pin_virtualcard_card_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tx_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('profit', 'Profit'), ('manual_credit', 'Manual Credit')], max_length=20),
        ),
    ]
